{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redrockbiometrics.palmid_sdk_flutter",
    "module": "palmid_sdk_flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.0.aar",
          "url": "palmid_sdk_flutter_release-1.0.aar",
          "size": 35630709,
          "sha512": "27035a0671fd7bf81327e8276fe4244ab25618a391f70513d1addbb40432b086e7926dcc13af5ff5144d8a8d271e5f3d6de5fbff0e00bea21a12ebd442bd9c0d",
          "sha256": "40cbc5b4b68642b97b8cdfee40e972ecc5930262059ee463228123c4549c6362",
          "sha1": "3c40d2621ed63aa231b0bd90ceb7af7668780677",
          "md5": "f4c163263efa8ed6609efc058ea7d644"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.0.aar",
          "url": "palmid_sdk_flutter_release-1.0.aar",
          "size": 35630709,
          "sha512": "27035a0671fd7bf81327e8276fe4244ab25618a391f70513d1addbb40432b086e7926dcc13af5ff5144d8a8d271e5f3d6de5fbff0e00bea21a12ebd442bd9c0d",
          "sha256": "40cbc5b4b68642b97b8cdfee40e972ecc5930262059ee463228123c4549c6362",
          "sha1": "3c40d2621ed63aa231b0bd90ceb7af7668780677",
          "md5": "f4c163263efa8ed6609efc058ea7d644"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.0-sources.jar",
          "url": "palmid_sdk_flutter_release-1.0-sources.jar",
          "size": 17318,
          "sha512": "ebaba9c99c1209863d5764c7c52162beea0675fac7c07111331ac81d0adceeb3cf2d17243242659cd05fec21111723feac9e7300444a86bf9289c1dbd290fdbd",
          "sha256": "581850e49cb1cec10a1fd29aab9b4aaf0641f6c5e03074ac042a71805ea33ac4",
          "sha1": "50af301974f34706e6148e80bea8fc723b685aa4",
          "md5": "7cc7dcf3bcfcd5c8b4473913f5ef84b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palmid_sdk_flutter_release-1.0-javadoc.jar",
          "url": "palmid_sdk_flutter_release-1.0-javadoc.jar",
          "size": 424334,
          "sha512": "50ea0802625a2af633223e5ec29467c701ffe45df23feebc8edd4ba6dc1a5baceb936ec70ba2bae237d8e41b065fc6ff30d4bb38899249730e9a13c2c411a75e",
          "sha256": "0ba6d66dcdf94a84833f3993f71bb2fe01ad9ca04ccdf7d6139d4da9a2ec0892",
          "sha1": "59b70f061cd31eb78732cb37bb515a04c8379d36",
          "md5": "faf23ff12f5d81fcc022ba4d8754b6d7"
        }
      ]
    }
  ]
}
